import { createSlice } from "@reduxjs/toolkit";
import fetchExchangeRates from "./api/ExchangeRatesApi";

// Define a Redux slice named "CoinExchangeSlice" for managing exchange rates.
const CoinExchangeSlice = createSlice({
  name: "ExchangeRates",
  initialState: {
    rates: {}, // Initialize rates as an empty object
    error: null, // Optionally, you can include an error field
  },
  reducers: {},
  extraReducers: (builder) => {
    // Handle the fulfilled action from the async thunk fetchExchangeRates
    builder.addCase(fetchExchangeRates.fulfilled, (state, action) => {
      // Set the rates in the state to the payload received from the async thunk.
      state.rates = action.payload;
    });

    // Handle the rejected action from the async thunk fetchExchangeRates
    builder.addCase(fetchExchangeRates.rejected, (state, action) => {
      // Handle any error and update the error field if needed.
      state.error = action.error.message;
    });
  },
});

// Export the reducer generated by the slice.
export default CoinExchangeSlice.reducer;
