import { createSlice } from '@reduxjs/toolkit';

// Create a Redux slice named "currencySlice" for managing currency selection.
const currencySlice = createSlice({
    name: 'currency',
    initialState: "usd", // Initialize the state with 'usd'
    reducers: {
        setCurrency: (state, action) => {
            // Update the state with the selected currency received from action.payload
            return action.payload;
        }
    }
})

export const { setCurrency } = currencySlice.actions; // Export the action creator
export default currencySlice.reducer; // Export the reducer generated by the slice
