import { createSlice } from "@reduxjs/toolkit";

// Create a Redux slice named "MarketSlice" for managing market-related data.
export const MarketSlice = createSlice({
    name: 'marketData',
    initialState: {
        time: 7, // Default time value
        coin: 'bitcoin', // Default coin value
        currency: 'USD', // Default currency value
    },
    reducers: {
        // Define reducers to update time, coin, and currency
        setTime: (state, action) => {
            // Update the time in the state with the value from the action
            return state.time = action.payload;
        },
        setCoin: (state, action) => {
            // Update the coin in the state with the value from the action
            return state.coin = action.payload;
        },
        setCurrency: (state, action) => {
            // Update the currency in the state with the value from the action
            return state.currency = action.payload;
        }
    }
});

// Export the action creators generated by the slice
export const { setTime, setCoin, setCurrency } = MarketSlice.actions;

// Export the reducer generated by the slice
export default MarketSlice.reducer;
